### ISSUE TITLE
600M-512px for comfyui not working 

### ISSUE THREAD

**Issue by Pancat009** [NVlabs/Sana#147]
I download the Sana_600M_512px model in /checkpoint,
and download the whole Sana_600M_512px_diffusers in /models/diffusers
and copy the vae from /Sana_600M_512px_diffusers/vae to models/vae 
but it repots error 

Error(s) in loading state_dict for SanaMS:
size mismatch for pos_embed: copying a param with shape torch.Size([1, 256, 1152]) from checkpoint, the shape in current model is torch.Size([1, 1024, 1152]).

![image](https://github.com/user-attachments/assets/e220c10a-75e2-45f0-a845-9fcb037c8692)

**Comment by lawrence-cj** [comment]
This bug should be fixed if you update the source code here: https://github.com/Efficient-Large-Model/ComfyUI_ExtraModels

Refer: https://github.com/NVlabs/Sana/issues/123

**Comment by Pancat009** [comment]
Thank you.
The image can be generated now, but not sure what mistake i've made, the image looks like this

![Image](https://github.com/user-attachments/assets/60155a4b-733d-462c-baf2-f56fd45bc93a)

**Comment by lawrence-cj** [comment]
Try to specify the precision when you load the weight. Like FP16 or BF16

Refer to: https://github.com/NVlabs/Sana/blob/main/asset/docs/model_zoo.md#-1-we-provide-all-the-links-of-sana-pth-and-diffusers-safetensor-below

**Comment by Pancat009** [comment]
I've tried to change resolution, gemma loader, vae type, vae dtype, arrange combination with each other, but still get the blur image.
changing the paramters in Ksampler has no effect neither

![Image](https://github.com/user-attachments/assets/68a137d6-fd46-4ad3-97dc-07d26053952e)

![Image](https://github.com/user-attachments/assets/314708d9-30fa-4653-82a3-a1595781d49b)

![Image](https://github.com/user-attachments/assets/3574b09a-a98d-41bc-8e54-ceb08482c883)
